using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutTabPanel : Control
{
    public LoadoutTabPanel(string name)
    {
        RobustXamlLoader.Load(this);
        Name = name;
    }
}
