using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutCustomizePanel : Control
{
    public event Action<SavedEventArgs>? OnSaved;
    public event Action<ColorChangedEventArgs>? OnColorChanged;

    public void SaveAll()
    {
        var args = new SavedEventArgs(
            string.IsNullOrEmpty(NameEdit.Text) ? null : NameEdit.Text,
            string.IsNullOrEmpty(Rope.Collapse(DescriptionEdit.TextRope))
                ? null
                : Rope.Collapse(DescriptionEdit.TextRope),
            ColorSelectorToggle.Pressed ? ColorEdit.Color.ToHex() : null);

        OnSaved?.Invoke(args);
    }

    public LoadoutCustomizePanel(string loadoutName, string loadoutDesc, Loadout preference, LoadoutPrototype prototype)
    {
        RobustXamlLoader.Load(this);

        SpecialName.Visible = prototype.CustomName;
        SpecialDescription.Visible = prototype.CustomDescription;
        ColorSelectorToggle.Visible = prototype.CustomColorTint;

        SaveButton.OnPressed += _ => SaveAll();
        ColorSelectorToggle.OnToggled += args => ColorEdit.Visible = args.Pressed;
        ColorEdit.OnColorChanged += _ =>
            OnColorChanged?.Invoke(new(ColorSelectorToggle.Pressed ? ColorEdit.Color.ToHex() : null));

        NameEdit.PlaceHolder = preference.CustomName ?? loadoutName;
        DescriptionEdit.Placeholder = new Rope.Leaf(preference.CustomDescription ?? loadoutDesc);
        if (preference.CustomColorTint is not null)
            ColorEdit.Color = Color.FromHex(preference.CustomColorTint);
    }

    public sealed class SavedEventArgs(string? name, string? description, string? color) : EventArgs
    {
        public string? CustomName = name;
        public string? CustomDescription = description;
        public string? CustomColor = color;
    }

    public sealed class ColorChangedEventArgs(string? color) : EventArgs
    {
        public string? Color = color;
    }
}
