using System.Linq;
using System.Text;
using Content.Client.Guidebook;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Content.Shared.Customization.Systems;
using Content.Shared.Labels.Components;
using Content.Shared.Paint;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutPreferenceSelector : Control
{
    public event Action<LoadoutPreference>? PreferenceChanged;

    public LoadoutPrototype Loadout { get; }
    public bool Valid;

    private readonly IEntityManager _entityManager;
    private readonly EntityUid _previewItemUid;

    private bool _showUnusable;
    private bool _wearable;
    private LoadoutPreference _preference = null!;
    private LoadoutCustomizePanel? _customizePanel;

    public bool ShowUnusable
    {
        get => _showUnusable;
        set
        {
            _showUnusable = value;
            Visible = Valid && _wearable || _showUnusable;
            PreferenceButton.RemoveStyleClass(StyleBase.ButtonDanger);
            PreferenceButton.AddStyleClass(Valid ? "" : StyleBase.ButtonDanger);
        }
    }

    public bool Wearable
    {
        get => _wearable;
        set
        {
            _wearable = value;
            Visible = Valid && _wearable || _showUnusable;
            PreferenceButton.RemoveStyleClass(StyleBase.ButtonCaution);
            PreferenceButton.AddStyleClass(_wearable ? "" : StyleBase.ButtonCaution);
        }
    }

    public LoadoutPreference Preference
    {
        get => _preference;
        set
        {
            _preference = value;
            if (value.CustomColorTint != null)
                UpdatePaint(
                    new(_previewItemUid, _entityManager.GetComponent<PaintedComponent>(_previewItemUid)), _entityManager);
            HeirloomButton.Pressed = value.CustomHeirloom ?? false;
            PreferenceButton.Pressed = value.Selected;
        }
    }

    public LoadoutPreferenceSelector(
        LoadoutPrototype loadout, JobPrototype highJob,
        HumanoidCharacterProfile profile, ref Dictionary<string, EntityUid> entities,
        IEntityManager entityManager, IPrototypeManager prototypeManager, IConfigurationManager configManager,
        CharacterRequirementsSystem characterRequirementsSystem, JobRequirementsManager jobRequirementsManager,
        LoadoutPreference preference
    ) : this(
        loadout, highJob, profile, ref entities, entityManager, prototypeManager, configManager,
        characterRequirementsSystem, jobRequirementsManager) =>
        Preference = preference;

    public LoadoutPreferenceSelector(
        LoadoutPrototype loadout, JobPrototype highJob,
        HumanoidCharacterProfile profile, ref Dictionary<string, EntityUid> entities,
        IEntityManager entityManager, IPrototypeManager prototypeManager, IConfigurationManager configManager,
        CharacterRequirementsSystem characterRequirementsSystem, JobRequirementsManager jobRequirementsManager
    )
    {
        RobustXamlLoader.Load(this);

        _entityManager = entityManager;
        Loadout = loadout;

        // Show/hide the special menu and items depending on what's allowed
        HeirloomButton.Visible = loadout.CanBeHeirloom;

        SpriteView previewLoadout;
        if (!entities.TryGetValue(loadout.ID + 0, out var dummyLoadoutItem))
        {
            // Get the first item in the loadout to be the preview
            dummyLoadoutItem = entityManager.SpawnEntity(loadout.Items.First(), MapCoordinates.Nullspace);
            entities.Add(loadout.ID + 0, dummyLoadoutItem);

            // Create a sprite preview of the loadout item
            previewLoadout = new()
            {
                Scale = new(1, 1),
                OverrideDirection = Direction.South,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1
            };
            previewLoadout.SetEntity(dummyLoadoutItem);
        }
        else
        {
            // Create a sprite preview of the loadout item
            previewLoadout = new()
            {
                Scale = new(1, 1),
                OverrideDirection = Direction.South,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1
            };
            previewLoadout.SetEntity(dummyLoadoutItem);
        }

        _previewItemUid = dummyLoadoutItem;

        entityManager.EnsureComponent<AppearanceComponent>(dummyLoadoutItem);
        entityManager.EnsureComponent<PaintedComponent>(dummyLoadoutItem, out var paint);

        var loadoutName =
            Loc.GetString($"loadout-name-{loadout.ID}") == $"loadout-name-{loadout.ID}"
                ? entityManager.GetComponent<MetaDataComponent>(dummyLoadoutItem).EntityName
                : Loc.GetString($"loadout-name-{loadout.ID}");

        // Display the item's label if it's present
        if (entityManager.TryGetComponent(dummyLoadoutItem, out LabelComponent? labelComponent))
        {
            var itemLabel = labelComponent.CurrentLabel;
            if (!string.IsNullOrEmpty(itemLabel))
                loadoutName += $" ({Loc.GetString(itemLabel)})";
        }

        var loadoutDesc = !Loc.TryGetString($"loadout-description-{loadout.ID}", out var description)
            ? entityManager.GetComponent<MetaDataComponent>(dummyLoadoutItem).EntityDescription
            : description;

        UpdateGuidebook();
        prototypeManager.PrototypesReloaded += _ => UpdateGuidebook();

        GuidebookButton.OnPressed += _ =>
        {
            if (!prototypeManager.TryIndex<GuideEntryPrototype>(loadout.GuideEntry, out var guideRoot))
                return;

            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
            //TODO: Don't close the guidebook if its already open, just go to the correct page
            guidebookController.ToggleGuidebook(
                new Dictionary<string, GuideEntry> { { loadout.GuideEntry, guideRoot } }, includeChildren: true,
                selected: loadout.GuideEntry);
        };

        // Create a checkbox to get the loadout
        PreferenceButton.AddChild(
            new BoxContainer
            {
                Children =
                {
                    new Label
                    {
                        Text = loadout.Cost.ToString(),
                        StyleClasses = { StyleBase.StyleClassLabelHeading },
                        MinWidth = 32,
                        MaxWidth = 32,
                        ClipText = true,
                        Margin = new(0, 0, 8, 0)
                    },
                    new PanelContainer
                    {
                        PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2f2f2f") },
                        Children = { previewLoadout }
                    },
                    new Label
                    {
                        Text = loadoutName,
                        Margin = new(8, 0, 0, 0)
                    }
                }
            });
        PreferenceButton.OnToggled += args =>
        {
            _preference.Selected = args.Pressed;
            PreferenceChanged?.Invoke(Preference);
        };
        HeirloomButton.OnToggled += args =>
        {
            _preference.CustomHeirloom = args.Pressed ? true : null;
            PreferenceChanged?.Invoke(Preference);
        };
        CustomizeButton.OnPressed += _ =>
        {
            if (_customizePanel is null)
            {
                CreateCustomizePanel(loadoutName, loadoutDesc, (dummyLoadoutItem, paint));
            }
            else
            {
                _customizePanel.SaveAll();
                Container.RemoveChild(_customizePanel);
                _customizePanel = null;
            }
        };

        var tooltip = new StringBuilder();
        // Add the loadout description to the tooltip if there is one
        if (!string.IsNullOrEmpty(loadoutDesc))
            tooltip.Append($"{Loc.GetString(loadoutDesc)}");

        // Get requirement reasons
        characterRequirementsSystem.CheckRequirementsValid(
            loadout.Requirements, highJob, profile, new(),
            jobRequirementsManager.IsWhitelisted(), loadout,
            entityManager, prototypeManager, configManager,
            out var reasons);

        // Add requirement reasons to the tooltip
        foreach (var reason in reasons)
            tooltip.Append($"\n{reason}");

        // Combine the tooltip and format it in the checkbox supplier
        if (tooltip.Length > 0)
        {
            var formattedTooltip = new Tooltip();
            formattedTooltip.SetMessage(FormattedMessage.FromMarkupPermissive(tooltip.ToString()));
            PreferenceButton.TooltipSupplier = _ => formattedTooltip;
        }

        return;

        // Manage the info button
        void UpdateGuidebook() =>
            GuidebookButton.Visible = prototypeManager.HasIndex<GuideEntryPrototype>(loadout.GuideEntry);
    }

    private void CreateCustomizePanel(string loadoutName, string loadoutDesc, Entity<PaintedComponent> loadoutItem)
    {
        var panel = new LoadoutCustomizePanel(loadoutName, loadoutDesc, _preference, Loadout);
        panel.OnSaved += args =>
        {
            _preference.CustomName = args.CustomName;
            _preference.CustomDescription = args.CustomDescription;
            _preference.CustomColorTint = args.CustomColor;
            _preference.Selected = PreferenceButton.Pressed;
            UpdatePaint(loadoutItem, _entityManager);
            PreferenceChanged?.Invoke(Preference);
        };

        panel.OnColorChanged += args =>
        {
            _preference.CustomColorTint = args.Color;
            UpdatePaint(loadoutItem, _entityManager);
        };

        _customizePanel = panel;
        Container.AddChild(panel);
    }

    private void UpdatePaint(Entity<PaintedComponent> entity, IEntityManager entityManager)
    {
        if (_preference.CustomColorTint != null)
        {
            entity.Comp.Color = Color.FromHex(_preference.CustomColorTint);
            entity.Comp.Enabled = true;
        }
        else
        {
            entity.Comp.Enabled = false;
        }

        var app = entityManager.System<SharedAppearanceSystem>();
        app.TryGetData(entity, PaintVisuals.Painted, out bool value);
        app.SetData(entity, PaintVisuals.Painted, !value);
    }
}
